import { stripCodeFences } from "../../visual-prompt/yaml-utils.js";

const SHOT_DIRECTOR_TASK = [
  "You are a Shot Director for VN CG illustrations.",
  "Input: VisualTokenBundle YAML + SceneAST context.",
  "Output: ShotGraph YAML ONLY. No markdown fences, no commentary, no image prompt prose.",
  "",
  "Output schema:",
  "camera:",
  "  angle:",
  "  distance:",
  "  lens:",
  "  framing:",
  "  dof:",
  "subject_blocking:",
  "  primary:",
  "  body_orientation:",
  "  face_visibility:",
  "frame_layout:",
  "  mirror_centered:",
  "  hips_lower_center:",
  "  hands_lower_frame:",
  "  subject_fill:",
  "depth_layers:",
  "  foreground: []",
  "  midground: []",
  "  background: []",
  "pov_constraints: []",
  "",
  "Rules:",
  "1. Output cinematography graph only — NEVER write final image prompt sentences.",
  "2. When face_mirror_only or mirror tokens present: face_visibility must be mirror_only.",
  "3. When no_player_body or player POV: pov_constraints must include no_player_body.",
  "4. If face visible only via mirror, pov_constraints must include hands_at_frame_edge_only — NOT hands visible outside mirror unless draft requires.",
  "5. All values English snake_case or short English labels.",
  "6. Use canonical camera slugs: dof must be shallow_dof (not shallow), framing tight_medium, distance intimate_distance.",
].join("\n");

const SHOT_DIRECTOR_EXAMPLE = [
  "Example output:",
  "camera:",
  "  angle: slight_downward",
  "  distance: intimate_distance",
  "  lens: 35mm",
  "  framing: tight_medium",
  "  dof: shallow_dof",
  "subject_blocking:",
  "  primary: lina",
  "  body_orientation: away_from_camera",
  "  face_visibility: mirror_only",
  "frame_layout:",
  "  mirror_centered: true",
  "  hips_lower_center: true",
  "  hands_lower_frame: true",
  "  subject_fill: 0.7",
  "depth_layers:",
  "  foreground:",
  "    - player_hands",
  "  midground:",
  "    - hips",
  "    - lower_back",
  "  background:",
  "    - mirror_face",
  "pov_constraints:",
  "  - no_player_body",
  "  - hands_at_frame_edge_only",
].join("\n");

export const SHOT_DIRECTOR_SYSTEM_PROMPT = [SHOT_DIRECTOR_TASK, "", SHOT_DIRECTOR_EXAMPLE].join("\n");

export function sanitizeShotGraphYaml(raw: string): string {
  return stripCodeFences(raw);
}
